### PR TITLE
Refactor Expressions

### PR DESCRIPTION
**Pull request by ruediste**
I refactored the Expression tree a bit: When I worked with the code I found some bugs and hacky snippets of code. I think the root causes were that 

- parameter types were represented as ParameterExpressions
- Lambda expressions were treated as expressions, although they do not fit in
- InvocationExpressions was split from InvocableExpression, causing all kinds of strange code

I moved quite some parts around got all unit tests running again. What do you think? I know it's hell of a large commit, but it's hard to split refactorings into smaller parts.

### CODE REVIEW

**Comment by kostat** [comment]
1. I indeed had some mess with parameter types and expressions. My idea was to have a better concept of parameters and arguments, but I didn't have time to bake it. (see more insights below)
2. The design decision to threat Lambda as Expression was borrowed from MS Linq. And it makes sense: lambda is a function, and if there is an expression representing a function, lambda is its "special case". In any case, can you elaborate the conflict?
3. I deliberately separated InvocationExpression from InvocableExpression (this was the only major API design split from MS if I recall right). The reason was to align better with how the logic goes, i.e. there is a concept of "function" - anything that receives arguments and returns a result. I called it InvocableExpression, which was a base for FieldExpression, MethodExpression and LambdaExpression. Its purpose is to describe parameters, result and "reference" the implementation. So potentially the parameters should be just types and not expressions. On the other hand InvocationExpression is the actual collection of arguments + reference to any InvocableExpression. Each argument can be an expression of any complexity. And of course I can have many different InvocationExpression referring the same Invocable.

So I need a serious argumentation to get convinced that Invocation and Invocable expressions should be combined.

**Comment by kostat** [comment]
@ruediste, if I was not clear - for a relatively small bug fix you introduced several conceptual changes and a lot of API breaking changes. Such change requires argumentation and some discussion even before we go to the details of the code. If you think that your approach is better than existing, please explain that!

**Comment by ruediste** [comment]
Sorry for the late reply, busy week...

In the meantime I looked further into the code and found more spots I'd like to change (and I'm on it).

I think the core question is: What is an Expression? I propose the following definition: 

> An expression is a function (in the mathematical sense) from an evaluation context to a value. 

The definition of "evaluation context" is more flexible and might depend on the use case, but for lambda expressions I'd propose it to contain the values for parameters, captured values and the this instance (not present for static lambdas/methods).

Using this definition, the InvocableExpression cannot be an Expression since it cannot be evaluated due to the missing definition of the arguments. (They are supplied by the InvocationExpression).

Furthermore, this definition avoids putting state into the expression tree (this reference), leading to simpler caching. (No need to replace the this instance after retrieving from cache).

All in all, my fork looks more and more like total conversion of the original code. I propose to wait 'till I'm through and get in contact again afterwards if I'm happy with the results.

**Comment by kostat** [comment]
My 2 cents:

1. It's always better to agree on design and API before writing the implementation code :-).
2. There is always more than 1 solution (design) to the same problem. This project takes the MS LINQ API design principles as its base because of these reasons:
 1. It does the same thing.
 1. They invested much more resources in its definition than I can possibly do.
 1. It's proved in many real apps as robust and users are happy with it.

See their [Expression](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expression(v=vs.110).aspx) 

So my suggestion is to explain either what is wrong with the current design, or why the new design will be so better to justify API breaks and potential risk to worsen some cases.

**Comment by kostat** [comment]
Made a quick fix, solving the problem you reported. While normalizing, there is no need to recourse into inner InvocationExpressions in order to not mess the parameter contexts. Though did not check what will happen if there will be deeper nesting with Lambdas.

**Pull request closed without merging**
